stackitcloud/terraform-provider-stackit

stackit/services/logme/logme_acc_test.go
stackit/services/mariadb/mariadb_acc_test.go
stackit/services/opensearch/opensearch_acc_test.go
stackit/services/postgresql/postgresql_acc_test.go
stackit/services/rabbitmq/rabbitmq_acc_test.go
stackit/services/redis/redis_acc_test.go

- Updates tests after change to use `plan_name` and `version` to compute `plan_id` in the provider

Fix DSA acceptance tests

---

docs/data-sources/objectstorage_credential.md
docs/resources/objectstorage_credential.md
go.mod
go.sum
stackit/internal/services/objectstorage/credential/datasource.go
stackit/internal/services/objectstorage/credential/resource.go
stackit/internal/services/objectstorage/credential/resource_test.go
stackit/internal/services/objectstorage/credentialsgroup/resource.go
stackit/internal/services/objectstorage/objectstorage_acc_test.go
stackit/internal/validate/validate.go
stackit/internal/validate/validate_test.go

- Credentials group logic wasn't fetching "credentials_group_id"
- Credential's "credentials_group_id" was set as "computed" in the data source schema
- Credential's "expiration_timestamp" was set as "required" in the data source schema
- Credential's "expiration_timestamp" is now RFC3339 without fractional seconds (API sometimes returns .000 in fractional seconds even if they're not 0) 
- Wrong checks in acc tests, also skipped import check on credential keys (can't be fetched fetched on import)
- Set retry limit for credential's unit test that uses mocked HTTP server (to be faster)

Object storage misc fixes

---

.github/workflows/release.yaml

- Add workflow_dispatch trigger
- Remove branch check. The check if not very necessary (we may want to release alpha/beta/other major versions from non-main branches) and as it's currently configured, goreleaser will run for all "v*" tags

Changes to release workflow

---

stackit/internal/services/ske/ske_acc_test.go

https://github.com/stackitcloud/terraform-provider-stackit/issues/124 has been fixed

SKE Acc tests - Remove max_surge from min cluster

---

stackit/internal/services/ske/cluster/resource.go
stackit/internal/services/ske/cluster/resource_test.go
stackit/internal/services/ske/ske_acc_test.go

- Fixes #134 
- Fix disabled extensions conversion
- Fix empty hibernations conversion
- Make `extensions.acl.cidrs` field optional

SKE Cluster: fix extensions and hibernations mapping

---

stackit/internal/services/objectstorage/credential/resource.go
stackit/internal/services/resourcemanager/project/resource.go

- Object storage credential custom endpoint was wrong
- Resource manager label value regex validation was wrong

Small fixes to Object Storage and Resource Manager

---

docs/resources/ske_cluster.md
examples/resources/stackit_ske_cluster/resource.tf
stackit/internal/services/ske/cluster/resource.go

Related to #202 
Removed cluster name regex validation for maintainability reasons. The API error message indicates what is a valid name, including the regex.
Replaced the `os_version` field in the ske cluster example with a placeholder for maintainability reasons.

Fix SKE example and remove cluster name regex validation

---

stackit/internal/services/argus/instance/resource.go

- `UseStateForUnknown` on the Argus instance plan ID field was causing an inconsistent result after applying an update using the plan name

Fix inconsistent result after updating Argus instance plan

---

.github/renovate.json

- So renovate PRs updating the STACKIT SDK modules are titled `Update STACKIT SDK modules` instead of just `Update SDK`

Update STACKIT SDK modules renovate group name

---

stackit/internal/services/ske/cluster/resource.go
stackit/internal/services/ske/ske_acc_test.go

The value might change if a cluster is created with a version <1.27 and then the new credentials process is triggered (either by creating a kubeconfig resource or externally through the Portal or API)

Remove UseStateForUnknown for kubeconfig field in ske cluster

---

stackit/internal/services/dns/recordset/resource.go
stackit/internal/validate/validate.go
stackit/internal/validate/validate_test.go

I've added a new validation `RecordSet` which takes into account the type type for validating the record value
Fixes https://github.com/stackitcloud/terraform-provider-stackit/issues/261

fix:  validates the record conent based on record type

---

stackit/internal/services/dns/recordset/resource.go

The valid length of a dns resource record name in the dns-stackit-api is 253 character.  
This was set to 63 character before by accident.
With this PR its also possible to create long rrset names with terraform.

DNS: Fix rrsetNameLength validation

---

stackit/internal/services/ske/cluster/resource.go

- These limits are subject to change in the API (and have changed recently), and since the error messages are clear we do not need to maintain these validations in the provider

Leave SKE cluster list length validations for the API

---

docs/data-sources/server_backup_schedule.md
docs/data-sources/server_backup_schedules.md
docs/guides/opting_into_beta_resources.md
docs/resources/server_backup_schedule.md
stackit/internal/features/beta.go
templates/guides/opting_into_beta_resources.md.tmpl

- Adjust note to be 
instead of
- Add links to resources from the opting into to beta resources guide

Improve beta resources documentation

---

stackit/internal/services/ske/cluster/resource.go
stackit/internal/services/ske/cluster/resource_test.go

- The API response always contains a mock date part in front of the time, so in case these are the same we just keep the current value in state (this part hasn't changed)
- What I changed was that now if the API response is different (not only in format but also in the actual time), this takes precedent over the state value as usual (instead of erroring)

Fix SKE cluster maintenance updated outside TF causing error

---

docs/data-sources/resourcemanager_project.md
docs/resources/resourcemanager_project.md
stackit/internal/services/resourcemanager/project/datasource.go
stackit/internal/services/resourcemanager/project/resource.go
stackit/internal/services/resourcemanager/project/resource_test.go

- Also adjusts `role` field description to match API behaviour
- Fixes backwards compatibility of deprecated `owner_email` field

Preserve order of project members even if API re-orders them

---

stackit/internal/services/postgresflex/instance/resource.go
stackit/internal/services/postgresflex/instance/use_state_for_unknown_if_flavor_unchanged_modifier.go

- Removes `UseStateForUnknown` from PostgreSQL Flex instance flavor ID and description as this caused an inconsistent result after apply on updates
- Adds a new `UseStateForUnknownIfFlavorUnchanged` plan modifier to the flavor ID and description fields that only sets the previous state value in the plan if the RAM and CPU values are unchanged (to prevent a `(known after apply)` planned change on every `terraform plan`)

Fix update of PostgreSQL Flex instance flavor

---

stackit/internal/validate/validate.go

The `rrule` validation requires `tzdata`. On environments like `alpine` (docker containers, Azure pipelines, etc.) the `tzdata` may be missing. 
This commit suggests embedding the `time/tzdata` into the terraform-provider validation, so the backup-schedule functionality (and any other future rrule validation) runs without problems on such environments. Otherwise the users will need to do lenghty debugging to be able to finally `apk add tzdata`.
This will add about ~400Kb to the size of the terraform provider.
Testing Done:
* ran linters, automated tests. Not sure how to add a test case for this.
* ran the following (it fails without embedding the `time/tzdata`)
```
[~/code/test-tzdata] cat Dockerfile
FROM alpine:latest
WORKDIR /app
COPY . .
RUN ./main
[~/code/test-tzdata] cat main.go …
```

Embed tzdata for rrule validation for alpine like env

---

docs/data-sources/loadbalancer.md
docs/resources/loadbalancer.md
stackit/internal/services/loadbalancer/loadbalancer/datasource.go
stackit/internal/services/loadbalancer/loadbalancer/resource.go

We have increased our maximum target count per pool from 250 to 1000.

Increase maximum Load Balancer target count to 1000 

---

stackit/internal/services/iaas/iaas_acc_test.go
stackit/internal/services/iaas/server/datasource.go
stackit/internal/services/iaas/server/resource.go
stackit/internal/services/iaas/server/resource_test.go

- After aligning withe IaaS team, we decide to remove this field to improve user experience and make it very clear and transparent how to setup networking for a server which is going to be done solely by separate network interface attachment resource

Remove initial networking field from server

---

stackit/internal/services/ske/cluster/resource.go

- Fixes an issue where the field is returned in the API response even if not configured in Terraform, which was causing an inconsistent result after apply
- This makes it Computed also (besides Optional), so the field will be `(known after apply)` on creation

fix: Make SKE cluster hibernations timezone field Computed

---

docs/guides/aws_provider_s3_stackit.md
templates/guides/aws_provider_s3_stackit.md.tmpl

This guide explains how to integrate the official AWS S3 Provider with our custom provider to manage STACKIT S3 Storage.  I used `make generate-docs` to regenerate the Terraform Registry documentation.

Docs: add docs to use aws s3 provider for stackit s3

---

stackit/internal/services/ske/cluster/resource.go

- Fixes an inconsistent result after apply in SKE cluster node pool taint value
- Error occured when a `stackit_ske_cluster.nodepool[x].taints[x].value` was left empty in the config, since the API returns `""` in this case (instead of not providing the field in the response)
- Making the field Computed is enough to fix the issue

Fix inconsistent result after apply in SKE cluster node pool taint value

---

docs/resources/ske_kubeconfig.md
stackit/internal/services/ske/kubeconfig/resource.go
stackit/internal/services/ske/kubeconfig/resource_test.go

- kubeconfig expires
- credentials rotation
- cluster recreation

Update kubeconfig when invalid

---

stackit/internal/services/iaas/server/resource.go

If you set "network_interfaces" in "stackit_server" and then apply an update to the server (e.g. if the name has changed), you will get an inconsistent result.

fix: Updating values of "stackit_server" leads to an inconsistent result

---

docs/resources/mariadb_instance.md
stackit/internal/services/mariadb/instance/resource.go

Update description of monitoring_instance_id

Extend MariaDB instance docs

---

docs/data-sources/ske_cluster.md
docs/resources/ske_cluster.md
stackit/internal/services/ske/cluster/datasource.go
stackit/internal/services/ske/cluster/resource.go
stackit/internal/services/ske/cluster/resource_test.go

Added the new attribute `egress_address_ranges` from the ske api to the terraform provider ressource.
I've adjusted the tests and run the commands:
make fmt
make test
I've also manually tested the changes by building the go binary and creating a new ske cluster. I've also checked that a user is able to downgrade/upgrade tf provider versions (back and forth from v.0.40 to this version and checked the state manually).
Thank you :-)

Feat: add egress_address_ranges attribute to ske resource

---

docs/guides/opting_into_beta_resources.md
templates/guides/opting_into_beta_resources.md.tmpl

Let's remove the list of beta resources in our docs. This list is not up to date and I don't see a good way to automate it.

Suggestion: remove list of beta resources

---

stackit/internal/services/objectstorage/credential/resource.go

fix: ```expiration_timestamp``` of ```stackit_objectstorage_credentials``` cannot be parsed, when no ```expiration_timestamp``` was set

fix: expiration_timestamp of "stackit_objectstorage_credentials" cannot be parsed

---

stackit/internal/services/iaas/networkinterface/resource.go

This has to be set to a nil value otherwise a name "" is sent via the next request which results in a failing validator
fixes #704

fix(network-interface): Response returns name "" if not set

---

stackit/internal/services/iaas/keypair/datasource.go

The provider response with a generic error when the key pair cannot be found (see #645). With this PR a more clear error message will be shown

fix: add error message that key pair doesn't exists

---

.github/workflows/tf-acc-test.yaml
stackit/internal/services/postgresflex/postgresflex_acc_test.go
stackit/internal/services/serverupdate/serverupdate_acc_test.go
stackit/internal/services/ske/ske_acc_test.go
stackit/internal/services/sqlserverflex/sqlserverflex_acc_test.go

fix(acceptance-tests): Postgresql use force delete
- use TF_ACC_REGION in acceptance test

fix(acceptance-tests): Postgresql use force delete

---

docs/resources/observability_instance.md
examples/resources/stackit_observability_instance/resource.tf

fix(observability): Observability example retention was in wrong order

---

stackit/internal/services/ske/ske_acc_test.go

fix(ske): Acceptance tests

---

stackit/internal/services/iaas/image/resource.go

fix(iaas): image waiter results in timeout

---

stackit/internal/services/iaas/network/resource.go

Applying the following terraform configuration
resource "stackit_network" "network" {
project_id         = var.project_id
name               = "example-network"
ipv4_nameservers   = ["192.0.2.0", "198.51.100.0", "203.0.113.0"]
ipv4_prefix_length = 24
}
causes an error
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to stackit_network.network, provider
│ "provider[\"registry.terraform.io/stackitcloud/stackit\"]" produced an unexpected new value:
│ .ipv4_prefix: was null, but now cty.StringVal("10.0.1.0/24").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵

fix(network): ipv4 prefix must be computed

---

README.md
docs/guides/aws_provider_s3_stackit.md
docs/guides/kubernetes_provider_ske.md
docs/guides/opting_into_beta_resources.md
docs/guides/ske_kube_state_metric_alerts.md
docs/guides/vault_secrets_manager.md
docs/index.md
examples/provider/provider.tf
stackit/internal/testutil/testutil.go
templates/guides/aws_provider_s3_stackit.md.tmpl
templates/guides/kubernetes_provider_ske.md.tmpl
templates/guides/opting_into_beta_resources.md.tmpl
templates/guides/ske_kube_state_metric_alerts.md.tmpl
templates/guides/vault_secrets_manager.md.tmpl

instead of deprecated 'region' attribute
~- [ ] Issue was linked above~
~- [ ] Examples were added / adjusted (see `examples/` directory)~
~- [ ] Unit tests got implemented or updated~
~- [ ] Acceptance tests got implemented or updated (see e.g. [here](https://github.com/stackitcloud/terraform-provider-stackit/blob/f5f99d170996b208672ae684b6da53420e369563/stackit/internal/services/dns/dns_acc_test.go))~

chore(docs): use new 'default_region' provider attribute

---

docs/data-sources/cdn_distribution.md
docs/resources/cdn_distribution.md
stackit/internal/services/cdn/distribution/datasource.go
stackit/internal/services/cdn/distribution/resource.go

Quick fix for cdn distribution resource that I recently submitted: Currently the only allowed value for backend should be "http", I added a validator to avoid issues. Since other values will be added in the future, I am using the "OneOf" validator

CDN distribution: add string validator for backend type

---

stackit/internal/services/observability/alertgroup/resource.go
stackit/internal/services/observability/log-alertgroup/resource.go
stackit/internal/services/ske/cluster/resource.go
stackit/internal/validate/validate.go
stackit/internal/validate/validate_test.go

The Observability API currently allows expressions with trailing newlines, which can lead to inconsistencies in the Terraform provider. I added a validation to inform users and suggest a workaround. The issue has been reported to the Observability team and is waiting to be fixed. In the meanwhile we are informing users with the workaround.
Case which is not working:
```terraform
resource "stackit_observability_alertgroup" "example" {
project_id  = var.stackit_project_id
instance_id = stackit_observability_instance.example.instance_id
name        = "TestAlertGroup"
interval    = "60m"
rules = [
{
alert      = "Check"
expression = <<EOT
(
kubelet_volume_stats_inodes_free{job="kubelet", namespace=~".*", metrics_path="/metrics"}
/
kubelet_volume_stats_inodes{job="kubelet", namespace=~".*", …
```

fix(alertgroups): add expression validator for alertgroups

---

docs/resources/cdn_custom_domain.md
docs/resources/cdn_distribution.md
examples/resources/stackit_cdn_custom_domain/resource.tf
examples/resources/stackit_cdn_distribution/resource.tf

Removes a comment above the example to keep all examples identical

docs(cdn): remove comment above example

---

stackit/internal/services/sqlserverflex/sqlserverflex_acc_test.go
stackit/internal/services/sqlserverflex/testdata/resource-max.tf
stackit/internal/services/sqlserverflex/testdata/resource-min.tf

Min/Max acceptance test for the sqlserverflex service
- ~~[ ] Examples were added / adjusted (see `examples/` directory)~~
- ~~[ ] Unit tests got implemented or updated~~

chore(sqlserverflex): implemented min/max test

---

stackit/internal/services/objectstorage/bucket/datasource.go
stackit/internal/services/objectstorage/bucket/resource.go
stackit/internal/services/objectstorage/credential/datasource.go
stackit/internal/services/objectstorage/credential/resource.go
stackit/internal/services/objectstorage/credentialsgroup/datasource.go
stackit/internal/services/objectstorage/credentialsgroup/resource.go
stackit/internal/services/objectstorage/utils/util.go
stackit/internal/services/objectstorage/utils/util_test.go

feat(objectstorage): set custom user-agent header for STACKIT API calls

---

stackit/internal/services/dns/recordset/datasource.go
stackit/internal/services/dns/recordset/resource.go
stackit/internal/services/dns/utils/util.go
stackit/internal/services/dns/utils/util_test.go
stackit/internal/services/dns/zone/datasource.go
stackit/internal/services/dns/zone/resource.go

feat(dns): set custom user-agent header for STACKIT API calls

---

stackit/internal/services/git/instance/datasource.go
stackit/internal/services/git/instance/resource.go
stackit/internal/services/git/utils/util.go
stackit/internal/services/git/utils/util_test.go

feat(git): set custom user-agent header for STACKIT API calls

---

stackit/internal/services/mariadb/credential/datasource.go
stackit/internal/services/mariadb/credential/resource.go
stackit/internal/services/mariadb/instance/datasource.go
stackit/internal/services/mariadb/instance/resource.go
stackit/internal/services/mariadb/utils/util.go
stackit/internal/services/mariadb/utils/util_test.go

feat(mariadb): set custom user-agent header for STACKIT API calls

---

stackit/internal/services/serverbackup/schedule/resource.go
stackit/internal/services/serverbackup/schedule/schedule_datasource.go
stackit/internal/services/serverbackup/schedule/schedules_datasource.go
stackit/internal/services/serverbackup/utils/util.go
stackit/internal/services/serverbackup/utils/util_test.go

feat(serverbackup): set custom user-agent header for STACKIT API calls

---

stackit/internal/services/postgresflex/database/datasource.go
stackit/internal/services/postgresflex/database/resource.go
stackit/internal/services/postgresflex/instance/datasource.go
stackit/internal/services/postgresflex/instance/resource.go
stackit/internal/services/postgresflex/user/datasource.go
stackit/internal/services/postgresflex/user/resource.go
stackit/internal/services/postgresflex/utils/util.go
stackit/internal/services/postgresflex/utils/util_test.go

feat(postgresflex): set custom user-agent header for STACKIT API calls

---

stackit/internal/services/opensearch/credential/datasource.go
stackit/internal/services/opensearch/credential/resource.go
stackit/internal/services/opensearch/instance/datasource.go
stackit/internal/services/opensearch/instance/resource.go
stackit/internal/services/opensearch/utils/util.go
stackit/internal/services/opensearch/utils/util_test.go

feat(opensearch): set custom user-agent header for STACKIT API calls

---

stackit/internal/services/loadbalancer/loadbalancer/datasource.go
stackit/internal/services/loadbalancer/loadbalancer/resource.go
stackit/internal/services/loadbalancer/observability-credential/resource.go
stackit/internal/services/loadbalancer/utils/util.go
stackit/internal/services/loadbalancer/utils/util_test.go

feat(loadbalancer): set custom user-agent header for STACKIT API calls

---

stackit/internal/services/secretsmanager/instance/datasource.go
stackit/internal/services/secretsmanager/instance/resource.go
stackit/internal/services/secretsmanager/user/datasource.go
stackit/internal/services/secretsmanager/user/resource.go
stackit/internal/services/secretsmanager/utils/util.go
stackit/internal/services/secretsmanager/utils/util_test.go

feat(secretsmanager): set custom user-agent header for STACKIT API calls

---

stackit/internal/services/sqlserverflex/instance/datasource.go
stackit/internal/services/sqlserverflex/instance/resource.go
stackit/internal/services/sqlserverflex/user/datasource.go
stackit/internal/services/sqlserverflex/user/resource.go
stackit/internal/services/sqlserverflex/utils/util.go
stackit/internal/services/sqlserverflex/utils/util_test.go

feat(sqlserverflex): set custom user-agent header for STACKIT API calls

---

stackit/internal/services/serviceaccount/account/datasource.go
stackit/internal/services/serviceaccount/account/resource.go
stackit/internal/services/serviceaccount/key/resource.go
stackit/internal/services/serviceaccount/token/resource.go
stackit/internal/services/serviceaccount/utils/util.go
stackit/internal/services/serviceaccount/utils/util_test.go

feat(serviceaccount): set custom user-agent header for STACKIT API calls

---

stackit/internal/services/modelserving/token/resource.go
stackit/internal/services/modelserving/utils/util.go
stackit/internal/services/modelserving/utils/util_test.go

feat(modelserving): set custom user-agent header for STACKIT API calls

---

stackit/internal/services/observability/alertgroup/datasource.go
stackit/internal/services/observability/alertgroup/resource.go
stackit/internal/services/observability/credential/resource.go
stackit/internal/services/observability/instance/datasource.go
stackit/internal/services/observability/instance/resource.go
stackit/internal/services/observability/log-alertgroup/datasource.go
stackit/internal/services/observability/log-alertgroup/resource.go
stackit/internal/services/observability/scrapeconfig/datasource.go
stackit/internal/services/observability/scrapeconfig/resource.go
stackit/internal/services/observability/utils/util.go
stackit/internal/services/observability/utils/util_test.go

feat(observability): set custom user-agent header for STACKIT API calls

---

stackit/internal/services/logme/credential/datasource.go
stackit/internal/services/logme/credential/resource.go
stackit/internal/services/logme/instance/datasource.go
stackit/internal/services/logme/instance/resource.go
stackit/internal/services/logme/utils/util.go
stackit/internal/services/logme/utils/util_test.go

feat(logme): set custom user-agent header for STACKIT API calls

---

stackit/internal/services/authorization/roleassignments/resource.go
stackit/internal/services/authorization/utils/util.go
stackit/internal/services/authorization/utils/util_test.go

feat(authorization): set custom user-agent header for STACKIT API calls

---

stackit/internal/services/redis/credential/datasource.go
stackit/internal/services/redis/credential/resource.go
stackit/internal/services/redis/instance/datasource.go
stackit/internal/services/redis/instance/resource.go
stackit/internal/services/redis/utils/util.go
stackit/internal/services/redis/utils/util_test.go

feat(redis): set custom user-agent header for STACKIT API calls

---

stackit/internal/services/cdn/customdomain/datasource.go
stackit/internal/services/cdn/customdomain/resource.go
stackit/internal/services/cdn/distribution/datasource.go
stackit/internal/services/cdn/distribution/resource.go
stackit/internal/services/cdn/utils/util.go
stackit/internal/services/cdn/utils/util_test.go

feat(cdn): set custom user-agent header for STACKIT API calls

---

stackit/internal/services/observability/observability_acc_test.go
stackit/internal/services/observability/testdata/resource-max.tf

This is not implemented and will be set to deprecated in the near future.
relates to #1234

fix(observability): Remove parameters from acc test

---

docs/resources/loadbalancer.md
stackit/internal/services/loadbalancer/loadbalancer/resource.go
stackit/internal/services/loadbalancer/loadbalancer/resource_test.go

fix(loadbalancer): set external_address as optional

---

docs/guides/stackit_org_service_account.md
docs/resources/resourcemanager_project.md
stackit/internal/services/resourcemanager/project/resource.go
templates/guides/stackit_org_service_account.md.tmpl

relates to #855
- [y] Examples were added / adjusted (see `examples/` directory)

chore(docs): add guide how to create service account in empty org

---

stackit/internal/services/objectstorage/bucket/resource.go

fix(objectstorage): handle bucket not empty error on bucket delete

---

.github/workflows/ci.yaml
.goreleaser.yaml

will help to detect deprecated options
Also updated deprecated archive format option for the goreleaser, see https://goreleaser.com/deprecations/#archivesformat
Without the update to the goreleaser config the pipeline failed as expected, because deprecated options were used, see https://github.com/stackitcloud/terraform-provider-stackit/actions/runs/15211187935/job/42785483545?pr=863

feat(ci): add check for goreleaser configuration

---

docs/guides/using_loadbalancer_with_observability.md
docs/resources/loadbalancer.md
docs/resources/server.md
examples/resources/stackit_loadbalancer/resource.tf
stackit/internal/services/iaas/server/const.go
templates/guides/using_loadbalancer_with_observability.md.tmpl

A small improvement for our docs :-)

docs: attach network interface via server attribute

---

docs/data-sources/loadbalancer.md
docs/resources/loadbalancer.md
examples/resources/stackit_loadbalancer/resource.tf
stackit/internal/services/loadbalancer/loadbalancer/datasource.go
stackit/internal/services/loadbalancer/loadbalancer/resource.go
stackit/internal/services/loadbalancer/loadbalancer/resource_test.go
stackit/internal/services/loadbalancer/loadbalancer_acc_test.go
stackit/internal/services/loadbalancer/testfiles/resource-max.tf

Added support for the plan_id field used to create or change a load balancer's plan to a higher one (e.g. p250, p750, ...).
Related: STACKITLB-250

feat(loadbalancer): Service Plan support for Load Balancers

---

stackit/internal/services/serviceaccount/token/resource.go

See 
https://docs.stackit.cloud/stackit/en/release-notes-23101442.html
https://docs.stackit.cloud/stackit/en/deprecation-plan-for-service-account-access-tokens-and-migration-guide-373293307.html

chore(sa-tokens): mark deprecation on sa-token resource

---

stackit/internal/services/ske/kubeconfig/resource.go
stackit/internal/services/ske/kubeconfig/resource_test.go

fix(kubeconfig): Region is not set correctly for Read()

---

stackit/internal/services/ske/kubeconfig/resource.go

fix: recreation of kubeconfig fails after migration

---

CONTRIBUTION.md
README.md
docs/index.md
docs/resources/service_account_access_token.md
examples/provider/provider.tf
stackit/internal/services/serviceaccount/token/resource.go
stackit/provider.go
templates/index.md.tmpl

See
https://docs.stackit.cloud/stackit/en/release-notes-23101442.html
https://docs.stackit.cloud/stackit/en/deprecation-plan-for-service-account-access-tokens-and-migration-guide-373293307.html

chore(provider): mark deprecation for service_account_token

---

docs/resources/sqlserverflex_user.md
stackit/internal/services/sqlserverflex/user/resource.go

fix(sqlserverflex): attribute rules is required not optional

---

docs/resources/loadbalancer.md
examples/resources/stackit_loadbalancer/resource.tf

´
The docs had a non working example for the advanced example because of the ipv4 prefix which is fixed now.

changed ipv4 prefix in resources loadbalancer.md to represent a working example

---

stackit/internal/services/iaasalpha/routingtable/route/resource.go
stackit/internal/services/iaasalpha/routingtable/table/resource.go

issue: the routing table resources will not be recreated if the default_region changes
relates to STACKITTPR-350

fix(iaas): region handling in routingtable resources didn't detect region changes

---

CONTRIBUTION.md
Makefile
README.md
stackit/internal/services/ske/ske_acc_test.go

docs: improve contribution docs
