stackitcloud/terraform-provider-stackit

go.mod, go.sum, stackit/internal/core/core.go, stackit/internal/services/secretsmanager/instance/datasource.go, stackit/internal/services/secretsmanager/instance/resource.go, stackit/internal/services/secretsmanager/instance/resource_test.go, stackit/internal/services/secretsmanager/secretsmanager_acc_test.go, stackit/internal/testutil/testutil.go, stackit/provider.go
ACL not implemented, will be added in a later PR
=> Implement Secrets Manager instance

stackit/internal/services/logme/instance/resource.go, stackit/internal/services/mariadb/instance/resource.go, stackit/internal/services/mongodbflex/instance/resource.go, stackit/internal/services/opensearch/instance/resource.go, stackit/internal/services/postgresflex/instance/resource.go, stackit/internal/services/postgresql/instance/resource.go, stackit/internal/services/rabbitmq/instance/resource.go, stackit/internal/services/redis/instance/resource.go, stackit/internal/services/ske/cluster/resource.go
=> Increase create and update timeouts for instances

README.md, templates/index.md.tmpl
This reverts commit 9ec45e6be8e8bb069f55c0415ce551b01b2a0286.
=> Revert "Add disclaimer to key flow doc (#73)"

go.mod, go.sum, stackit/internal/core/core.go, stackit/internal/services/loadbalancer/loadbalancer/resource.go, stackit/internal/services/loadbalancer/loadbalancer/resource_test.go, stackit/provider.go
- Adds resource schema and model
- Adds `toCreatePayload` and tests
=> Onboard Load Balancer (part 1: implement creation payload helpers)

stackit/internal/services/ske/cluster/resource.go, stackit/internal/services/ske/cluster/resource_test.go, stackit/internal/services/ske/ske_acc_test.go
Fixes https://github.com/stackitcloud/terraform-provider-stackit/issues/110
=> SKE Cluster - Change field model lists to use types.List

stackit/internal/core/core.go, stackit/internal/services/argus/instance/resource.go, stackit/internal/services/argus/scrapeconfig/resource.go, stackit/internal/services/dns/recordset/resource.go, stackit/internal/services/dns/zone/resource.go, stackit/internal/services/loadbalancer/loadbalancer/resource.go, stackit/internal/services/logme/instance/resource.go, stackit/internal/services/mariadb/instance/resource.go, stackit/internal/services/mongodbflex/instance/resource.go, stackit/internal/services/mongodbflex/user/resource.go, stackit/internal/services/objectstorage/credential/resource.go, stackit/internal/services/opensearch/instance/resource.go, stackit/internal/services/postgresflex/instance/resource.go, stackit/internal/services/postgresflex/user/resource.go, stackit/internal/services/postgresql/instance/resource.go, stackit/internal/services/rabbitmq/instance/resource.go, stackit/internal/services/redis/instance/resource.go, stackit/internal/services/resourcemanager/project/resource.go, stackit/internal/services/secretsmanager/instance/resource.go, stackit/internal/services/secretsmanager/user/resource.go, stackit/internal/services/ske/cluster/resource.go
- When converting a terraform model value to Go pointer, if the value is unknown set it to nil
=> Replace terraform ValuePointer function with custom pointer conversion function

stackit/internal/services/ske/cluster/resource.go
=> Move checkAllowPriviledgedContainers to the Create and Update functions in the SKE resource

docs/data-sources/objectstorage_credentials_group.md, stackit/internal/services/objectstorage/credentialsgroup/datasource.go
=> Fix data source credentials group field description

docs/data-sources/loadbalancer.md, docs/resources/loadbalancer.md, stackit/internal/services/loadbalancer/loadbalancer/datasource.go, stackit/internal/services/ske/cluster/resource.go, stackit/internal/services/ske/kubeconfig/resource.go
- get cluster kubeconfig in cluster Read
- add default of 3600s to kubeconfig resource
- missing docs update
=> Get credentials in cluster read and add default to kubeconfig expiration

stackit/internal/services/ske/cluster/resource.go
=> Return available ske versions in the error message

examples/resources/stackit_secretsmanager_user/resource.tf
=> Fix secretsmanager_user resource example

stackit/internal/services/dns/recordset/resource.go
=> fix: set min ttl to 60

docs/resources/ske_project.md, stackit/internal/services/ske/project/resource.go
Description and deprecation message has been extended with the information about using terraform state rm.
=> Update SKE project resource deprecation message

stackit/internal/services/dns/recordset/resource.go
=> DNS Record set type requires replace

stackit/internal/services/postgresflex/instance/resource.go
=> Support storage class update in postgresflex

docs/data-sources/logme_credential.md, docs/data-sources/mariadb_credential.md, docs/data-sources/opensearch_credential.md, docs/data-sources/postgresql_credential.md, docs/data-sources/rabbitmq_credential.md, docs/data-sources/redis_credential.md, docs/resources/logme_credential.md, docs/resources/mariadb_credential.md, docs/resources/opensearch_credential.md, docs/resources/postgresql_credential.md, docs/resources/rabbitmq_credential.md, docs/resources/redis_credential.md, stackit/internal/services/logme/credential/datasource.go, stackit/internal/services/logme/credential/resource.go, stackit/internal/services/mariadb/credential/datasource.go, stackit/internal/services/mariadb/credential/resource.go, stackit/internal/services/opensearch/credential/datasource.go, stackit/internal/services/opensearch/credential/resource.go, stackit/internal/services/postgresql/credential/datasource.go, stackit/internal/services/postgresql/credential/resource.go, stackit/internal/services/rabbitmq/credential/datasource.go, stackit/internal/services/rabbitmq/credential/resource.go, stackit/internal/services/redis/credential/datasource.go, stackit/internal/services/redis/credential/resource.go, stackit/internal/services/ske/project/datasource.go, stackit/internal/services/ske/project/resource.go
Related to https://github.com/stackitcloud/terraform-provider-stackit/issues/276
=> Remove ssl note from redis credentials uri, mark uri as sensitive and update ske project deprecation date

stackit/internal/services/ske/cluster/resource.go, stackit/internal/services/ske/cluster/resource_test.go
=> Fix cluster network mapping

examples/resources/stackit_argus_instance/resource.tf, stackit/internal/services/argus/instance/resource.go, stackit/internal/services/argus/instance/resource_test.go
Reverts stackitcloud/terraform-provider-stackit#401
=> Revert "Improve Argus metrics data retention policy"

.github/workflows/release.yaml, .github/workflows/renovate.yaml
Reverts stackitcloud/terraform-provider-stackit#400
=> Revert "Update Github action and Go releaser"

docs/resources/ske_cluster.md, stackit/internal/services/ske/cluster/resource.go
=> Add note regarding update of SKE cluster node pools

stackit/internal/utils/utils.go
=> Fix field string validators

docs/guides/outgoing_ske_ip.md, templates/guides/outgoing_ske_ip.md.tmpl
I wrote some documentation on how to gather the outgoing IP address of the SKE cluster for my own reference. I believe this could be helpful for other developers as well. Please feel free to read through it and share any feedback if something is not clear.
Additionally, I suggest we link this guide to the following issue for better visibility: [Issue #102](https://github.com/stackitcloud/terraform-provider-stackit/issues/102).
Thank you! :-)
=> Guide to retrieve ske outgoing cluster ip

CONTRIBUTION.md, main.go
Added support for debug flag and appropriate documentation
=> feat: support and document attaching a debugger to the provider

stackit/internal/services/iaas/server/datasource.go, stackit/internal/services/iaas/server/datasource_test.go
separated the models of resource and datasource to handle individual attributes correctly
=> fix: separated models for resource and data-source

stackit/internal/services/ske/kubeconfig/resource.go
When migrating from an old provider version, the missing creation time confuses the kubeconfig resource
=> fix: handle undefined creation time

stackit/internal/services/iaas/image/resource.go
relates to STACKITTPR-70
---
Not sure how this could be unit tested as we would need some file dummy to upload. Would be thankful for some hints on that 😄
=> fix: use file inputstream on file upload instead of in-memory buffer

docs/data-sources/sqlserverflex_user.md, docs/resources/sqlserverflex_user.md, stackit/internal/services/sqlserverflex/user/datasource.go, stackit/internal/services/sqlserverflex/user/resource.go
Added the new sql-server roles to the terraform provider ressource.
I've run the commands:
make fmt
make test
Thank you :-)
relates to STACKITTPR-114
=> feat: add new sql-server roles

stackit/internal/services/iaas/server/resource.go
=> fix(iaas): delete_on_termination produces an unexpected new value

.github/pull_request_template.md, Makefile
=> chore(github): add pull request template

.github/workflows/ci.yaml, CONTRIBUTION.md, go.mod
=> chore: upgraded go version

docs/resources/sqlserverflex_instance.md, docs/resources/sqlserverflex_user.md, examples/resources/stackit_sqlserverflex_instance/resource.tf, stackit/internal/services/sqlserverflex/user/resource.go
relates to STACKITTPR-169 / #729
=> chore(sqlserverflex): docs adjustments

stackit/internal/services/serverbackup/schedule/resource.go, stackit/internal/services/serverupdate/schedule/resource.go, stackit/internal/services/serviceaccount/account/datasource.go, stackit/internal/services/serviceaccount/account/resource.go, stackit/internal/services/serviceaccount/key/resource.go, stackit/internal/services/serviceaccount/token/resource.go
will cause issues when debugging
relates to STACKITTPR-206
=> fix(beta): remove caching of beta checks

.github/pull_request_template.md, .github/workflows/ci.yaml, docs/data-sources/observability_scrapeconfig.md, scripts/check-docs.sh
=> feat(ci): ensure docs are up-to-date on PRs

stackit/internal/services/mariadb/mariadb_acc_test.go, stackit/internal/services/mariadb/testfiles/resource-max.tf, stackit/internal/services/mariadb/testfiles/resource-min.tf, stackit/internal/testutil/testutil.go, stackit/internal/testutil/testutil_test.go
=> feat(MariaDB): Min/Max acceptance test

docs/resources/loadbalancer.md, stackit/internal/services/loadbalancer/loadbalancer/resource.go, stackit/internal/services/loadbalancer/loadbalancer_acc_test.go, stackit/internal/services/loadbalancer/testfiles/resource-max.tf, stackit/internal/services/loadbalancer/testfiles/resource-min.tf
=> feat(Loadbalancer): Min/Max acceptance tests

stackit/internal/services/observability/alertgroup/resource.go, stackit/internal/services/observability/instance/datasource.go, stackit/internal/services/observability/log-alertgroup/resource.go, stackit/internal/services/observability/observability_acc_test.go, stackit/internal/services/observability/testdata/resource-max.tf, stackit/internal/services/observability/testdata/resource-min.tf
=> feat(observability): Min/Max acceptance tests

README.md
=> fix(readme): update indent

docs/data-sources/service_account.md, docs/resources/service_account.md, docs/resources/service_account_access_token.md, docs/resources/service_account_key.md, stackit/internal/services/serviceaccount/account/datasource.go, stackit/internal/services/serviceaccount/account/resource.go, stackit/internal/services/serviceaccount/key/resource.go, stackit/internal/services/serviceaccount/token/resource.go
Confident to move this code to GA.
=> chore: remove beta state from service account

stackit/internal/services/logme/logme_acc_test.go, stackit/internal/services/logme/testdata/resource-max.tf, stackit/internal/services/logme/testdata/resource-min.tf
Min/Max acceptance test for logme api
- ~~[ ] Examples were added / adjusted (see `examples/` directory)~~
- ~~[ ] Unit tests got implemented or updated~~
=> chore(acceptance test): logme acceptance tests

docs/data-sources/objectstorage_bucket.md, docs/data-sources/objectstorage_credential.md, docs/data-sources/objectstorage_credentials_group.md, docs/resources/objectstorage_bucket.md, docs/resources/objectstorage_credential.md, docs/resources/objectstorage_credentials_group.md, stackit/internal/services/objectstorage/bucket/datasource.go, stackit/internal/services/objectstorage/bucket/resource.go, stackit/internal/services/objectstorage/bucket/resource_test.go, stackit/internal/services/objectstorage/credential/datasource.go, stackit/internal/services/objectstorage/credential/datasource_test.go, stackit/internal/services/objectstorage/credential/resource.go, stackit/internal/services/objectstorage/credential/resource_test.go, stackit/internal/services/objectstorage/credentialsgroup/datasource.go, stackit/internal/services/objectstorage/credentialsgroup/resource.go, stackit/internal/services/objectstorage/credentialsgroup/resource_test.go, stackit/internal/services/objectstorage/objectstorage_acc_test.go, stackit/internal/services/objectstorage/testfiles/resource-min.tf
=> feat(objectstorage): Min/Max acceptance tests

docs/resources/mongodbflex_instance.md, examples/resources/stackit_mongodbflex_instance/resource.tf, stackit/internal/services/mongodbflex/instance/resource.go, stackit/internal/services/mongodbflex/mongodbflex_acc_test.go
=> feat(mongodb): set point_in_time_window_hours as required

stackit/internal/services/iaas/image/datasource.go, stackit/internal/services/iaas/image/resource.go, stackit/internal/services/iaas/keypair/resource.go, stackit/internal/services/iaas/network/datasource.go, stackit/internal/services/iaas/network/resource.go, stackit/internal/services/iaas/networkarea/resource.go, stackit/internal/services/iaas/networkarearoute/resource.go, stackit/internal/services/iaas/networkinterface/resource.go, stackit/internal/services/iaas/publicip/resource.go, stackit/internal/services/iaas/securitygroup/resource.go, stackit/internal/services/iaas/server/datasource.go, stackit/internal/services/iaas/server/resource.go, stackit/internal/services/iaas/utils/util.go, stackit/internal/services/iaas/utils/util_test.go, stackit/internal/services/iaas/volume/resource.go
=> chore(iaas): extract mapping of labels into util func

docs/index.md, stackit/internal/core/core.go, stackit/internal/testutil/testutil.go, stackit/provider.go, stackit/provider_acc_test.go, stackit/testdata/provider-all-attributes.tf, stackit/testdata/provider-credentials.tf, stackit/testdata/provider-invalid-attribute.tf
=> feat(provider): Added acceptance tests

stackit/internal/services/observability/instance/resource.go
=> fix(observability): timeout updating alert config

docs/data-sources/cdn_distribution.md, docs/resources/cdn_distribution.md, examples/data-sources/stackit_cdn_distribution/data-source.tf, examples/resources/stackit_cdn_distribution/resource.tf, stackit/internal/services/cdn/cdn_acc_test.go, stackit/internal/services/cdn/distribution/datasource.go, stackit/internal/services/cdn/distribution/resource.go, stackit/internal/services/cdn/distribution/resource_test.go
Implement image optimizer for READ, CREATE and UPDATE in CDN service
https://jira.schwarz/browse/STACKITCDN-838
=> feat: implement image optimizer in cdn service

docs/data-sources/mongodbflex_instance.md, docs/data-sources/mongodbflex_user.md, docs/resources/mongodbflex_instance.md, docs/resources/mongodbflex_user.md, go.mod, go.sum, stackit/internal/services/mongodbflex/instance/datasource.go, stackit/internal/services/mongodbflex/instance/resource.go, stackit/internal/services/mongodbflex/instance/resource_test.go, stackit/internal/services/mongodbflex/mongodbflex_acc_test.go, stackit/internal/services/mongodbflex/user/datasource.go, stackit/internal/services/mongodbflex/user/datasource_test.go, stackit/internal/services/mongodbflex/user/resource.go, stackit/internal/services/mongodbflex/user/resource_test.go, stackit/internal/services/mongodbflex/utils/util.go, stackit/internal/services/mongodbflex/utils/util_test.go
=> feat(mongodbflex): region adjustment

MIGRATION.md, docs/guides/ske_kube_state_metric_alerts.md, docs/guides/ske_log_alerts.md, docs/resources/network_area.md, docs/resources/ske_cluster.md, examples/resources/stackit_network_area/resource.tf, examples/resources/stackit_ske_cluster/resource.tf, templates/guides/ske_kube_state_metric_alerts.md.tmpl, templates/guides/ske_log_alerts.md.tmpl
=> Update network_area and ske documentation and examples

docs/resources/observability_instance.md, stackit/internal/services/observability/instance/resource.go
=> chore(observability): Add detailed informations to global config

docs/data-sources/image_v2.md, docs/data-sources/machine_type.md, stackit/internal/services/iaas/imagev2/datasource.go, stackit/internal/services/iaas/machinetype/datasource.go
Improves docs for our customers
=> chore(docs): improve docs for image_v2 and machine_type
